// Code generated by mockery v2.50.0. DO NOT EDIT.

package cfgutils

import (
	cfgutils "github.com/fujitsu/docker-machine-driver-fsas/cfgutils"
	mock "github.com/stretchr/testify/mock"
)

// MockCfgManager is an autogenerated mock type for the CfgManager type
type MockCfgManager struct {
	mock.Mock
}

type MockCfgManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCfgManager) EXPECT() *MockCfgManager_Expecter {
	return &MockCfgManager_Expecter{mock: &_m.Mock}
}

// ExtendUserdataRunCmd provides a mock function with given fields: commands
func (_m *MockCfgManager) ExtendUserdataRunCmd(commands []string) error {
	ret := _m.Called(commands)

	if len(ret) == 0 {
		panic("no return value specified for ExtendUserdataRunCmd")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]string) error); ok {
		r0 = rf(commands)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCfgManager_ExtendUserdataRunCmd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtendUserdataRunCmd'
type MockCfgManager_ExtendUserdataRunCmd_Call struct {
	*mock.Call
}

// ExtendUserdataRunCmd is a helper method to define mock.On call
//   - commands []string
func (_e *MockCfgManager_Expecter) ExtendUserdataRunCmd(commands interface{}) *MockCfgManager_ExtendUserdataRunCmd_Call {
	return &MockCfgManager_ExtendUserdataRunCmd_Call{Call: _e.mock.On("ExtendUserdataRunCmd", commands)}
}

func (_c *MockCfgManager_ExtendUserdataRunCmd_Call) Run(run func(commands []string)) *MockCfgManager_ExtendUserdataRunCmd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockCfgManager_ExtendUserdataRunCmd_Call) Return(_a0 error) *MockCfgManager_ExtendUserdataRunCmd_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCfgManager_ExtendUserdataRunCmd_Call) RunAndReturn(run func([]string) error) *MockCfgManager_ExtendUserdataRunCmd_Call {
	_c.Call.Return(run)
	return _c
}

// ExtendUserdataWriteFiles provides a mock function with given fields: fileObjects
func (_m *MockCfgManager) ExtendUserdataWriteFiles(fileObjects []cfgutils.CloudConfigItem) error {
	ret := _m.Called(fileObjects)

	if len(ret) == 0 {
		panic("no return value specified for ExtendUserdataWriteFiles")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]cfgutils.CloudConfigItem) error); ok {
		r0 = rf(fileObjects)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCfgManager_ExtendUserdataWriteFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtendUserdataWriteFiles'
type MockCfgManager_ExtendUserdataWriteFiles_Call struct {
	*mock.Call
}

// ExtendUserdataWriteFiles is a helper method to define mock.On call
//   - fileObjects []cfgutils.CloudConfigItem
func (_e *MockCfgManager_Expecter) ExtendUserdataWriteFiles(fileObjects interface{}) *MockCfgManager_ExtendUserdataWriteFiles_Call {
	return &MockCfgManager_ExtendUserdataWriteFiles_Call{Call: _e.mock.On("ExtendUserdataWriteFiles", fileObjects)}
}

func (_c *MockCfgManager_ExtendUserdataWriteFiles_Call) Run(run func(fileObjects []cfgutils.CloudConfigItem)) *MockCfgManager_ExtendUserdataWriteFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]cfgutils.CloudConfigItem))
	})
	return _c
}

func (_c *MockCfgManager_ExtendUserdataWriteFiles_Call) Return(_a0 error) *MockCfgManager_ExtendUserdataWriteFiles_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCfgManager_ExtendUserdataWriteFiles_Call) RunAndReturn(run func([]cfgutils.CloudConfigItem) error) *MockCfgManager_ExtendUserdataWriteFiles_Call {
	_c.Call.Return(run)
	return _c
}

// IsInit provides a mock function with no fields
func (_m *MockCfgManager) IsInit() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsInit")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockCfgManager_IsInit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsInit'
type MockCfgManager_IsInit_Call struct {
	*mock.Call
}

// IsInit is a helper method to define mock.On call
func (_e *MockCfgManager_Expecter) IsInit() *MockCfgManager_IsInit_Call {
	return &MockCfgManager_IsInit_Call{Call: _e.mock.On("IsInit")}
}

func (_c *MockCfgManager_IsInit_Call) Run(run func()) *MockCfgManager_IsInit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCfgManager_IsInit_Call) Return(_a0 bool) *MockCfgManager_IsInit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCfgManager_IsInit_Call) RunAndReturn(run func() bool) *MockCfgManager_IsInit_Call {
	_c.Call.Return(run)
	return _c
}

// PrepareMetadata provides a mock function with given fields: instanceId, hostname
func (_m *MockCfgManager) PrepareMetadata(instanceId string, hostname string) string {
	ret := _m.Called(instanceId, hostname)

	if len(ret) == 0 {
		panic("no return value specified for PrepareMetadata")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(instanceId, hostname)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockCfgManager_PrepareMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareMetadata'
type MockCfgManager_PrepareMetadata_Call struct {
	*mock.Call
}

// PrepareMetadata is a helper method to define mock.On call
//   - instanceId string
//   - hostname string
func (_e *MockCfgManager_Expecter) PrepareMetadata(instanceId interface{}, hostname interface{}) *MockCfgManager_PrepareMetadata_Call {
	return &MockCfgManager_PrepareMetadata_Call{Call: _e.mock.On("PrepareMetadata", instanceId, hostname)}
}

func (_c *MockCfgManager_PrepareMetadata_Call) Run(run func(instanceId string, hostname string)) *MockCfgManager_PrepareMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockCfgManager_PrepareMetadata_Call) Return(_a0 string) *MockCfgManager_PrepareMetadata_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCfgManager_PrepareMetadata_Call) RunAndReturn(run func(string, string) string) *MockCfgManager_PrepareMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// PrepareRke2ConfigScript provides a mock function with given fields: configName, machineUUID
func (_m *MockCfgManager) PrepareRke2ConfigScript(configName string, machineUUID string) string {
	ret := _m.Called(configName, machineUUID)

	if len(ret) == 0 {
		panic("no return value specified for PrepareRke2ConfigScript")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(configName, machineUUID)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockCfgManager_PrepareRke2ConfigScript_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareRke2ConfigScript'
type MockCfgManager_PrepareRke2ConfigScript_Call struct {
	*mock.Call
}

// PrepareRke2ConfigScript is a helper method to define mock.On call
//   - configName string
//   - machineUUID string
func (_e *MockCfgManager_Expecter) PrepareRke2ConfigScript(configName interface{}, machineUUID interface{}) *MockCfgManager_PrepareRke2ConfigScript_Call {
	return &MockCfgManager_PrepareRke2ConfigScript_Call{Call: _e.mock.On("PrepareRke2ConfigScript", configName, machineUUID)}
}

func (_c *MockCfgManager_PrepareRke2ConfigScript_Call) Run(run func(configName string, machineUUID string)) *MockCfgManager_PrepareRke2ConfigScript_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockCfgManager_PrepareRke2ConfigScript_Call) Return(_a0 string) *MockCfgManager_PrepareRke2ConfigScript_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCfgManager_PrepareRke2ConfigScript_Call) RunAndReturn(run func(string, string) string) *MockCfgManager_PrepareRke2ConfigScript_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCfgManager creates a new instance of MockCfgManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCfgManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCfgManager {
	mock := &MockCfgManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
