// Code generated by mockery v2.53.6. DO NOT EDIT.

package seedutils

import (
	seedutils "github.com/fujitsu/docker-machine-driver-fsas/seedutils"
	mock "github.com/stretchr/testify/mock"
)

// MockSeedManager is an autogenerated mock type for the SeedManager type
type MockSeedManager struct {
	mock.Mock
}

type MockSeedManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSeedManager) EXPECT() *MockSeedManager_Expecter {
	return &MockSeedManager_Expecter{mock: &_m.Mock}
}

// CleanupFolderWithConfigFiles provides a mock function with given fields: dmiSystemUUID, ip
func (_m *MockSeedManager) CleanupFolderWithConfigFiles(dmiSystemUUID string, ip string) error {
	ret := _m.Called(dmiSystemUUID, ip)

	if len(ret) == 0 {
		panic("no return value specified for CleanupFolderWithConfigFiles")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(dmiSystemUUID, ip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSeedManager_CleanupFolderWithConfigFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupFolderWithConfigFiles'
type MockSeedManager_CleanupFolderWithConfigFiles_Call struct {
	*mock.Call
}

// CleanupFolderWithConfigFiles is a helper method to define mock.On call
//   - dmiSystemUUID string
//   - ip string
func (_e *MockSeedManager_Expecter) CleanupFolderWithConfigFiles(dmiSystemUUID interface{}, ip interface{}) *MockSeedManager_CleanupFolderWithConfigFiles_Call {
	return &MockSeedManager_CleanupFolderWithConfigFiles_Call{Call: _e.mock.On("CleanupFolderWithConfigFiles", dmiSystemUUID, ip)}
}

func (_c *MockSeedManager_CleanupFolderWithConfigFiles_Call) Run(run func(dmiSystemUUID string, ip string)) *MockSeedManager_CleanupFolderWithConfigFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockSeedManager_CleanupFolderWithConfigFiles_Call) Return(_a0 error) *MockSeedManager_CleanupFolderWithConfigFiles_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSeedManager_CleanupFolderWithConfigFiles_Call) RunAndReturn(run func(string, string) error) *MockSeedManager_CleanupFolderWithConfigFiles_Call {
	_c.Call.Return(run)
	return _c
}

// IsActive provides a mock function with no fields
func (_m *MockSeedManager) IsActive() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsActive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSeedManager_IsActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsActive'
type MockSeedManager_IsActive_Call struct {
	*mock.Call
}

// IsActive is a helper method to define mock.On call
func (_e *MockSeedManager_Expecter) IsActive() *MockSeedManager_IsActive_Call {
	return &MockSeedManager_IsActive_Call{Call: _e.mock.On("IsActive")}
}

func (_c *MockSeedManager_IsActive_Call) Run(run func()) *MockSeedManager_IsActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSeedManager_IsActive_Call) Return(_a0 error) *MockSeedManager_IsActive_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSeedManager_IsActive_Call) RunAndReturn(run func() error) *MockSeedManager_IsActive_Call {
	_c.Call.Return(run)
	return _c
}

// IsInit provides a mock function with no fields
func (_m *MockSeedManager) IsInit() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsInit")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockSeedManager_IsInit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsInit'
type MockSeedManager_IsInit_Call struct {
	*mock.Call
}

// IsInit is a helper method to define mock.On call
func (_e *MockSeedManager_Expecter) IsInit() *MockSeedManager_IsInit_Call {
	return &MockSeedManager_IsInit_Call{Call: _e.mock.On("IsInit")}
}

func (_c *MockSeedManager_IsInit_Call) Run(run func()) *MockSeedManager_IsInit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSeedManager_IsInit_Call) Return(_a0 bool) *MockSeedManager_IsInit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSeedManager_IsInit_Call) RunAndReturn(run func() bool) *MockSeedManager_IsInit_Call {
	_c.Call.Return(run)
	return _c
}

// PublishFile provides a mock function with given fields: dmiSystemUUID, ip, filename, content
func (_m *MockSeedManager) PublishFile(dmiSystemUUID string, ip string, filename seedutils.ConfigFiles, content []byte) error {
	ret := _m.Called(dmiSystemUUID, ip, filename, content)

	if len(ret) == 0 {
		panic("no return value specified for PublishFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, seedutils.ConfigFiles, []byte) error); ok {
		r0 = rf(dmiSystemUUID, ip, filename, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSeedManager_PublishFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishFile'
type MockSeedManager_PublishFile_Call struct {
	*mock.Call
}

// PublishFile is a helper method to define mock.On call
//   - dmiSystemUUID string
//   - ip string
//   - filename seedutils.ConfigFiles
//   - content []byte
func (_e *MockSeedManager_Expecter) PublishFile(dmiSystemUUID interface{}, ip interface{}, filename interface{}, content interface{}) *MockSeedManager_PublishFile_Call {
	return &MockSeedManager_PublishFile_Call{Call: _e.mock.On("PublishFile", dmiSystemUUID, ip, filename, content)}
}

func (_c *MockSeedManager_PublishFile_Call) Run(run func(dmiSystemUUID string, ip string, filename seedutils.ConfigFiles, content []byte)) *MockSeedManager_PublishFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(seedutils.ConfigFiles), args[3].([]byte))
	})
	return _c
}

func (_c *MockSeedManager_PublishFile_Call) Return(_a0 error) *MockSeedManager_PublishFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSeedManager_PublishFile_Call) RunAndReturn(run func(string, string, seedutils.ConfigFiles, []byte) error) *MockSeedManager_PublishFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSeedManager creates a new instance of MockSeedManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSeedManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSeedManager {
	mock := &MockSeedManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
