apiVersion: rke-machine-config.cattle.io/v1
kind: FsasConfig
metadata:
  name: {{ printf "%s-all" .Values.cluster.name }}
  namespace: fleet-default

apiUrl: ""
tenantUuid: ""
credentialsUsername: ""
credentialsPassword: ""
dnsIp: ""
ntpUrl: ""
slesRegistrationCode: ""
slesRegistrationEmail: ""

networkBaremetalUuid: {{ required "networkBaremetalUuid is required" .Values.fsas.pool.networkBaremetalUuid | quote }}
networkProvisionUuid: {{ required "networkProvisionUuid is required" .Values.fsas.pool.networkProvisionUuid | quote }}
networkProvisionDefaultGw: {{ required "networkProvisionDefaultGw is required" .Values.fsas.pool.networkProvisionDefaultGw | quote }}
enableBaremetalBonding: {{ .Values.fsas.pool.enableBaremetalBonding }}
sshUser: {{ required "sshUser is required" .Values.fsas.pool.sshUser | quote }}
sshPassword: {{ required "sshPassword is required" .Values.fsas.pool.sshPassword | quote }}
osImageName: {{ required "osImageName is required" .Values.fsas.pool.osImageName | quote }}
imageOsSshHostPubKey: {{ required "imageOsSshHostPubKey is required" .Values.fsas.pool.imageOsSshHostPubKey | quote }}
userdata: {{ .Values.fsas.pool.userdata | quote }}
computeConditionsJson: {{ required "computeConditionsJson is required" .Values.fsas.pool.computeConditionsJson | trim | squote }}
devicesSpecJson: {{ required "devicesSpecJson is required" .Values.fsas.pool.devicesSpecJson | quote }}


