cluster:
  name: <cluster-name>
  cloudCredentialSecretName: cattle-global-data:<cloud-credentials-ID>
  kubernetesVersion: v1.35.6+rke2r1

machinePools:
  pool:
    name: <node-name>
    quantity: 1
    controlPlaneRole: true
    etcdRole: true
    workerRole: true

rkeConfig:
  cni: calico
  ingressController: traefik
  disableKubeProxy: false
  etcdExposeMetrics: false

  etcd:
    snapshotRetention: 5
    snapshotScheduleCron: "0 */5 * * *"

  upgradeStrategy:
    controlPlaneConcurrency: "1"
    workerConcurrency: "1"

machineSelectorConfig:
  protectKernelDefaults: false

fsas:
  pool:
    networkBaremetalUuid: <network-baremetal-uuid>
    networkProvisionUuid: <network-provision-uuid>
    networkProvisionDefaultGw: <network-provision-default-gw>
    enableBaremetalBonding: <true-or-false>
    sshUser: <ssh-user-name>
    sshPassword: <ssh-user-password>
    osImageName: <os-image-name>
    imageOsSshHostPubKey: <ssh-public-key>
    userdata: ""
    computeConditionsJson: |
      <compute-conditions-json>
    devicesSpecJson: |
      <devices-spec-json>
