cluster:
  name: ""
  # cloudCredentialSecretName refers to ID of the cloud credential
  cloudCredentialSecretName: cattle-global-data:""
  kubernetesVersion: v1.35.6+rke2r1
  localClusterAuthEndpoint: {}

rkeConfig:
  cni: calico
  ingressController: traefik
  disableKubeProxy: false
  etcdExposeMetrics: false

  etcd:
    snapshotRetention: 5
    snapshotScheduleCron: "0 */5 * * *"

controlPlane:
  enabled: true
  quantity: 1
  # Set to true for a single-node cluster
  workerRole: false

worker:
  enabled: true
  quantity: 1

fsas:
  controlPlane:
    networkBaremetalUuid: ""
    networkProvisionUuid: ""
    networkProvisionDefaultGw: ""
    enableBaremetalBonding: false
    osImageName: ""
    sshUser: ""
    sshPassword: ""
    imageOsSshHostPubKey: ""
    userdata: ""
    computeConditionsJson: >
      []
    devicesSpecJson: >
      []

  worker:
    networkBaremetalUuid: ""
    networkProvisionUuid: ""
    networkProvisionDefaultGw: ""
    enableBaremetalBonding: false
    osImageName: ""
    imageOsSshHostPubKey: ""
    sshUser: ""
    sshPassword: ""
    userdata: ""
    computeConditionsJson: >
      []
    devicesSpecJson: >
      []
