name: CodeQL
on:
  push:
    branches:
      - feature/set_explicitly_permisions_in_workflow_files

jobs:
  codeql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
