# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Display Go version
      run: go version
    - name: Install dependencies
      run: go get .
    - name: Set build flag
      run: echo "CGO_ENABLED=0" >> $CGO_ENABLED
    - name: Build
      run: go build -o docker-machine-driver-fsas .
    - name: Test
      run: go test ./...
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: docker-machine-driver-fsas
        path: docker-machine-driver-fsas
