# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Display Go version
      run: go version
    - name: Install dependencies
      run: go get .
    - name: Build
      run: go build -o docker-machine-driver-fsas .
      env:
        CGO_ENABLED: "0"
    - name: Test
      run: go test ./...
    - name: Create node driver YAML
      run: bash ./ci_tools/generate_nodedriver_yaml.sh
    - name: Upload binary and YAML
      uses: actions/upload-artifact@v4
      with:
        name: docker-machine-driver-fsas-artifact
        path: |
          docker-machine-driver-fsas
          docker-machine-driver-fsas.yml
        retention-days: 14
        if-no-files-found: warn
