name: Setup and test
on:
  push:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.22'
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: go get .
      - name: Test
        run: go test ./...
